[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
itertools = "0.13.0"
regex = { version = "1.11.1", features = ["std"] }
